export { default as NavbarComp } from './NavbarComp'
export { default as HeaderComp } from './HeaderComp'
export { default as DealsComp } from './DealsComp'
export { default as HighlightsComp } from './HighlightsComp'
export { default as TestimonialsComp } from './TestimonialsComp'
export { default as FeatureComp } from './FeatureComp'
export { default as NewsletterComp } from './NewsletterComp'
